[package]
name = "rucomfyui_node_graph"
version = "0.1.0"
edition = "2021"
description = "A recreation of the ComfyUI node graph in Rust using `egui` and `rucomfyui`."
authors = ["Philpax <me@philpax.me>"]
license = "MIT"

[dependencies]
egui = "0.29"
# TODO: Use a released version of egui_node_graph2 once https://github.com/trevyn/egui_node_graph2/issues/4 is fixed
egui_node_graph2 = { git = "https://github.com/trevyn/egui_node_graph2.git", rev = "3c6eb3c", features = [
    "persistence",
] }

# We don't need the typed nodes, so we are opting out of them
rucomfyui = { path = "../rucomfyui", default-features = false }

serde = { workspace = true, optional = true }

[features]
default = []
serde = ["dep:serde"]
