name: Rust CI

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: rustfmt

      - name: Check formatting
        run: cargo fmt --all -- --check

      - name: Run Clippy without features
        run: cargo clippy --all --no-default-features -- -D warnings

      - name: Run Clippy with typed_nodes
        run: cargo clippy --all --features typed_nodes -- -D warnings

      - name: Run tests with features
        run: cargo test --all --features typed_nodes
