name: Rust CI

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Run Clippy without features
        run: cargo clippy --no-default-features -- -D warnings

      - name: Run Clippy
        run: cargo clippy -- -D warnings

      - name: Run tests with features
        run: cargo test
